version: '3.7'

x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "5"

x-ulimits: &default-ulimits
  memlock:
    soft: -1
    hard: -1
  nofile:
    soft: 65536
    hard: 65536

services:
  es01:
    image: elasticsearch:7.17.0
    container_name: es01
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - logger.restcontroller.level=error
      - discovery.zen.minimum_master_nodes=2
      - ${ELASTICSEARCH_OPTIONS}
    volumes:
      - ./data/01:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elastic
    logging: *default-logging
    ulimits: *default-ulimits
    restart: unless-stopped
    cap_add:
      - IPC_LOCK
    deploy:
      resources:
        limits:
          memory: ${ELASTICSEARCH_MEMORY}

  es02:
    image: elasticsearch:7.17.0
    container_name: es02
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - logger.restcontroller.level=error
      - discovery.zen.ping.unicast.hosts=es01
      - discovery.zen.minimum_master_nodes=2
      - ${ELASTICSEARCH_OPTIONS}
    volumes:
      - ./data/02:/usr/share/elasticsearch/data
    networks:
      - elastic
    logging: *default-logging
    ulimits: *default-ulimits
    restart: unless-stopped
    cap_add:
      - IPC_LOCK
    deploy:
      resources:
        limits:
          memory: ${ELASTICSEARCH_MEMORY}

  es03:
    image: elasticsearch:7.17.0
    container_name: es03
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - logger.restcontroller.level=error
      - discovery.zen.ping.unicast.hosts=es01
      - discovery.zen.minimum_master_nodes=2
      - ${ELASTICSEARCH_OPTIONS}
    volumes:
      - ./data/03:/usr/share/elasticsearch/data
    networks:
      - elastic
    logging: *default-logging
    ulimits: *default-ulimits
    restart: unless-stopped
    cap_add:
      - IPC_LOCK
    deploy:
      resources:
        limits:
          memory: ${ELASTICSEARCH_MEMORY}

networks:
  elastic:
    driver: bridge
